[toolchain]
channel = "1.91.1"
components = [
    "rustfmt",
    "clippy",
    # https://github.com/dtolnay/trybuild?tab=readme-ov-file#troubleshooting
    "rust-src",
]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-musl"]